---
- name: Disable Swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^/#/' /etc/fstab
  become: true

- name: Load kernel modules
  copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'

- name: Load overlay module
  modprobe:
    name: overlay
    state: present

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Apply sysctl parameters for Kubernetes
  copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    mode: '0644'

- name: Reload sysctl
  command: sysctl --system
  become: true

# ---------------------------------------------------------------------
# Containerd cleanup and install (exact match to working script)
# ---------------------------------------------------------------------

- name: Stop containerd service
  systemd:
    name: containerd
    state: stopped
  ignore_errors: true

- name: Remove old containerd packages
  apt:
    name:
      - containerd
      - containerd.io
    state: absent
  ignore_errors: true

- name: Remove old containerd config dir
  file:
    path: /etc/containerd
    state: absent
  ignore_errors: true

- name: Download containerd 1.6.27 .deb package
  get_url:
    url: https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/containerd.io_1.6.27-1_amd64.deb
    dest: /tmp/containerd.io_1.6.27-1_amd64.deb
    mode: '0644'

- name: Install containerd 1.6.27
  apt:
    deb: /tmp/containerd.io_1.6.27-1_amd64.deb

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate default containerd config
  shell: containerd config default | tee /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Set SystemdCgroup to true
  replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)SystemdCgroup = false'
    replace: '\1SystemdCgroup = true'

- name: Reexec systemd to avoid containerd reload issues
  command: systemctl daemon-reexec

- name: Restart and enable containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: Configure crictl to use containerd socket
  copy:
    dest: /etc/crictl.yaml
    content: |
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
      timeout: 10
      debug: false
    mode: '0644'

# ---------------------------------------------------------------------
# Kubernetes APT Repo Setup
# ---------------------------------------------------------------------

- name: Ensure directory for apt keyrings exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Kubernetes GPG key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
    filename: kubernetes
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold Kubernetes packages to prevent automatic upgrade
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
