- name: Install required packages
  yum:
    name:
      - curl
      - ca-certificates
      - gnupg2
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
    update_cache: yes

- name: Disable SELinux temporarily
  command: setenforce 0
  when: ansible_selinux.status == "enabled"

- name: Disable SELinux permanently
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=disabled'

- name: Add Kubernetes YUM repository
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl

- name: Install Kubernetes packages
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes

- name: Check installed Kubernetes version
  command: kubeadm version -o short
  register: kubeadm_version

- debug:
    var: kubeadm_version.stdout

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Install containerd
  yum:
    name: containerd
    state: present

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: yes
    state: started

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Turn off swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^/#/' /etc/fstab
